# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

### BINDEOS GENERALES ###

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu


### BINDEOS PARA MOVER LAS VENTANAS ###

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d


bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d


bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

### ARRANCAMOS DISTINTAS COSITAS ###

exec-once = systemctl --user start hyprpolkitagent.service
exec-once = swayosd-server
exec-once = waybar

## ARRANCAMOS WALLPAPERS ANIMADOS PARA AMBOS MONITORES ##

exec-once = mpvpaper -o "no-audio loop panscan=1" DP-1 ~/Pictures/Wallpapers/astronauta.mp4
exec-once = mpvpaper -o "no-audio loop panscan=1" HDMI-A-1 ~/Pictures/Wallpapers/astronauta.mp4

### TECLADO EN ESPAÑOL ####

input {
kb_layout = es
}

### Configuracion para mis cascos HyprX Cloud II ###

bindel = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bindel = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bindel = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

### DEFINO LOS ESCRITORIOS ###

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

### ASIGNO LOS ESCRITORIOS A LOS MONITORES ###

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1


### DEFINO LA POSICION DE LOS MONITORES ###

monitor = DP-1, 2560x1440@60, 1920x0, 1.0
monitor = HDMI-A-1, 1920x1080@60, 0x0, 1.0

### CONFIGURO PARA HACER CAPTURAS DE PANTALLA ###
## CAPTURA DE LA REGION DE LA PANTALLA ## 
bind = , Print, exec, pgrep slurp || grim -g "$(slurp)" - | swappy -f -

## CAPTURA DE LA PANTALLA COMPLETA AL PORTAPAPELES ##
bind = SHIFT, Print, exec, grim - | wl-copy

## CAPTURA DE LA VENTANA ACTIVA ##
bind = $mainMod, Print, exec, grim -g "$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')" - | swappy -f -


### PAUSAR EL VIDEO DE LA OTRA PANTALLA ###

bind = , KP_Subtract, exec, playerctl --player=brave,firefox,chromium,mpv play-pause

### TECLA 9 DEL TECLADO NUMERICO PARA MUTEARME EL MICRO ###

bind = , KP_9, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bind = , KP_Prior, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle




###################### CONFIGS ESTETICAS ########################

### REBORDES VENTANAS ###

general {
    border_size = 2
    col.active_border = rgba(0000ffff) rgba(0055ffff) rgba(00aaffff) rgba(00eaffff) rgba(0080ffff) rgba(6600ffff) rgba(0000ffff) 45deg
    col.inactive_border = rgba(595959aa)
}

animation = borderangle, 1, 200, linear, loop

decoration {
    rounding = 10
}
